### ISSUE TITLE
Password plaintext not bcrypt hash while create new user

### ISSUE THREAD

**Issue by yudhatp** [nyancodeid/laravel-8-stisla-jetstream#1]
while create new user (route user/new) , password value are plain text not bcrypt hash..
ketika membuat user baru via form create user, isi kolom password tidak terhash bcrypt..

**Comment by nyancodeid** [comment]
Whopss, thanks udah di ingetin. @yudhatp bisa bikin pull-request nya?

Let me know kalau bisa.
