### ISSUE TITLE
Bisakah Stisla ini di aplikasikan untuk SPA ?

### ISSUE THREAD

**Issue by taqius** [nyancodeid/laravel-8-stisla-jetstream#10]
hai lagi master, saya melihat ada turbo link di dalam aplikasi ini , apakah turbo link disini dapat digunakan dan bisa mengaplikasikan SPA ?
karena di livewire 2 turbolink sudah di tiadakan.
kalau pun bisa, boleh minta tolong berikan sedikit contoh kisi-kisi atau cara menggunakan turbolink untuk SPA di aplikasi ini ?
terima kasih atas perhatiannya.

**Comment by nyancodeid** [comment]
Bisa, di versi Livewire 2 ini, support turbolink out of the box emang udah dihilangkan jadi kita harus setup manual turbolinknya. Kalau dokumentasi Livewire nya kita cuma nambah turbolinks adapter di bagian bawah script livewire. Tinggal setup beberapa hal sesuai kebutuhan yang diperlukan agar SPA nya lancar.

Baca disini cara upgradenya.
[https://laravel-livewire.com/docs/2.x/upgrading#turbolinks](https://laravel-livewire.com/docs/2.x/upgrading#turbolinks)
