### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by addhes** [nyancodeid/laravel-8-stisla-jetstream#15]
misi om mau tanya, ini kenapa ya eror Trying to access array offset on value of type null,

Trying to access array offset on value of type null (View: \laravel-8-stisla-jetstream\resources\views\pages\student\student-data.blade.php)

pas di dd di bagian $data = $this->get_pagination_data(); datanya null,

**Comment by nyancodeid** [comment]
Untuk menampilkan data dari table `student` silahkan tambahkan kondisi untuk `case "student":` dulu sesuai contoh ya. Kalau disini saya contohkan untuk `case "users":`

https://github.com/nyancodeid/laravel-8-stisla-jetstream/blob/f7e669652918a5bde585a18a0a5374aac37b46c8/app/Traits/WithDataTable.php

Jadi file diatas nanti dipakai di Livewire Component pada file 

https://github.com/nyancodeid/laravel-8-stisla-jetstream/blob/master/app/Http/Livewire/Table/Main.php

**Comment by addhes** [comment]
work, terima kasih om,

**Comment by nyancodeid** [comment]
> work, terima kasih om,

sama sama
