### ISSUE TITLE
Populate data into datatable using json response

### ISSUE THREAD

**Issue by lordnaz** [nyancodeid/laravel-8-stisla-jetstream#16]
Hi, Thanks for this great project. I'm in love with this jetstream + stisla. I just want to ask, how exactly do we populate data if we are using response from REST API instead of direct access query from DB? Any idea on how to populate data to the table using such way?

**Comment by nyancodeid** [comment]
Thank you, and good question. I never try this solution before, but it still make sense i think. So if you made REST API request inside of Laravel / Livewire Component you can place it on `app\Http\Livewire\Table\Main.php`. But we have another problem, to use `Livewire\WithPagination` we must have data with typeof `Illuminate\Pagination\Paginator` from Laravel. I think, you need to convert your HTTP API response to Paginator first before Livewire can use it.

And i also consider if you mean is to make a request from the client side. You can call an API first from Javascript and passed it into Livewire component using `@this.emit` or `@this.call` methods and process it on Livewire Component. And again you must convert data response into Paginator first. 

References:
- https://laravel.com/docs/8.x/pagination#manually-creating-a-paginator
- https://laravel-livewire.com/docs/2.x/pagination
- https://laravel-livewire.com/docs/2.x/events

**Comment by lordnaz** [comment]
Hi, Thanks for your kind response. By the way, I just found another solution for this, but it will not be using the pre-made component and traits u made from this project. But it's a pretty (direct solution) with few customization and a little help of few CDN and jQuery. Just want to share this here if someone later, can find this useful as an option for using datatables in this project.

### CSS :
`https://cdnjs.cloudflare.com/ajax/libs/datatables.net-bs4/1.1.0/dataTables.bootstrap4.css`
`https://cdnjs.cloudflare.com/ajax/libs/datatables.net-select-bs4/1.3.3/select.bootstrap4.css`

### JS : 
`https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js`
`https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js`
`https://cdn.datatables.net/select/1.3.1/js/select.bootstrap4.min.js`

### UserController.php :
![image](https://user-images.githubusercontent.com/83264713/129458244-674fabba-7d38-43fb-b5d3-e5d2ae510bd7.png)

### dashboard.blade.php
![image](https://user-images.githubusercontent.com/83264713/129458636-06ad783c-2098-48aa-afd6-806ed8905196.png)

### dashboard-table.blade.php
![image](https://user-images.githubusercontent.com/83264713/129458648-9844f7f3-5ecd-4517-925f-566dca22a3a4.png)

### Outcome : 
![image](https://user-images.githubusercontent.com/83264713/129458601-c4b0a9c8-f036-4e14-aee9-4bd0fde77005.png)

**Comment by nyancodeid** [comment]
Wow, It's look awesome. Thanks for sharing the solution to us. I will leave this issue/question open for now, just in case any body have similar case like you. Good job @lordnaz, appreciate it.
