### ISSUE TITLE
Teams? How do I add teams support?

### ISSUE THREAD

**Issue by Slabar** [nyancodeid/laravel-8-stisla-jetstream#17]
How do I add teams support?

Thx

**Comment by nyancodeid** [comment]
You can follow this suggest from StackOverflow. I'm not sure it's gonna work like expected but still worth to try. Make sure you backup or try it somewhere else.

https://stackoverflow.com/questions/65600071/installing-teams-support-in-laravel-jetstream-after-initial-install
