### ISSUE TITLE
Suggestion: Voyager admin like replacement?

### ISSUE THREAD

**Issue by jechaviz** [nyancodeid/laravel-8-stisla-jetstream#5]
Can this project grows up to replace [voyager admin](https://github.com/the-control-group/voyager), or take some concepts or libraries from them to make something like that? Or libaries like this?
https://github.com/kdion4891/laravel-livewire-forms
Thank you.

**Comment by nyancodeid** [comment]
It could, why not. But the purpose of this repository is not like that. The purpose of this repository itself is to make it easier for us to start laravel-8 + jetstream and livewire + stisla admin templates without having to configure from scratch.

I have personally tried `laravel-livewire-forms` but there isn't much customizable and it doesn't quite match what I need. Indeed, making forms will be faster, but we can't do much customization there.

If you have more experience and have a secret recipe for how to solve it, we can collaborate here.
