### ISSUE TITLE
Many to many eloquent

### ISSUE THREAD

**Issue by taqius** [nyancodeid/laravel-8-stisla-jetstream#7]
Saya mencoba membuat many to many eloquent  dengan table pegawai, keterangan, dan pemasukan. Kalau saya run dengan view table tanpa render dari table.Main data bisa muncul normal seutuhnya. Tapi ketika saya masukkan ke dalam table.main selalu error array of null. Kenapa ya kira kira??

**Comment by nyancodeid** [comment]
Hi, tolong kasih penjelasan lebih ya. seperti ekspektasi yang tampil apa, potongan kode nya gimana dan error yang tampil apa.

**Comment by taqius** [comment]
ekspektasi yang di inginkan dengan many to many kemarin adalah.menampilkan nama pegawai, keterangan pekerjaan dari tabel pemasukan yang mengambil data dari pegawai via pegawai_id, dan keterangan via keterangan_id.  error yang tampil cuma array of null
sekarang sudah solved, akhirnya menggunakan one to many. terima kasih stisla jetstream nya sangat berguna untuk keperluan pribadai saya. semangat mimin ~!
